{% set name = "pixelator" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pixelgentechnologies/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fad3bfb00620e0c8fd5a15a4add1876d5b603d212fbbc50f80e75c34e1d949a8

build:
  entry_points:
    - pixelator = pixelator.cli:main_cli
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script: |
    {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('pixelator', max_pin="x.x") }}

requirements:
  host:
    - python >=3.10,<3.12
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.1
    - pip
  run:
    - python >=3.10,<3.12
    - click
    - yapf
    - cutadapt >=4.2
    - umi_tools <=1.1.4
    - pyfastx
    - yappi
    - pandas >=2.0.0,<3.0.0
    - numpy <1.24.0
    - python-annoy <=1.17.0
    - esda
    - libpysal >=4.9.2
    - xopen
    - anndata >=0.8.0
    - numba >=0.56.4
    - scanpy
    - lxml
    - cssselect
    - typing_extensions
    - scipy
    - pyarrow >=13,<15
    - semver >=3.0.0,<4.0.0
    - ruamel.yaml >=0.17.21,<0.18.0
    - pydantic >=1.10.7,<2.0.0
    - polars >=0.19.0,<0.20.0
    - importlib-resources >=5.12.0,<6.0.0
    - fsspec >=2023.9.0,<2024.0.0
    - fastparquet >=2023.8.0,<2024.0.0
    - graspologic >=3.3.0,<4.0.0
    - fastp
    - zlib-ng

test:
  imports:
    - pixelator
  commands:
    - pip check
    - pixelator --help
    - pixelator --version | grep -E "^pixelator, version {{ version }}$"
  requires:
    - pip

about:
  home: https://github.com/PixelgenTechnologies/pixelator
  summary: |
     A command-line tool and library to process and analyze sequencing data from Molecular Pixelation (MPX) assays.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  maintainers:
    - fbdtemme
    - johandahlberg
    - ambarrio
